version: "0.5"

# Production configuration
# Start with: process-compose -f process-compose.prod.yaml up

log_configuration:
  rotation:
    max_size_mb: 10
    max_age_days: 30
    max_backups: 10
  location: ./logs
  add_timestamp: false

processes:
  bot:
    # TODO: Remove tee workaround once https://github.com/F1bonacc1/process-compose/issues/361 is fixed
    # The flush_each_line option doesn't work, so we manually tee logs for real-time file output
    command: bash -c "mkdir -p ./logs && exec bun src/main.ts 2>&1 | tee -a ./logs/bot-prod.log"
    availability:
      restart: "on_failure"
      backoff_seconds: 5
      max_restarts: 10
    environment:
      - NODE_ENV=production