version: "0.5"

processes:
  bot:
    # TODO: Remove tee workaround once https://github.com/F1bonacc1/process-compose/issues/361 is fixed
    # The flush_each_line option doesn't work, so we manually tee logs for real-time file output
    command: bash -c "mkdir -p ./logs && exec bun --watch src/main.ts 2>&1 | tee -a ./logs/bot-dev.log"
    availability:
      restart: "on_failure"
      backoff_seconds: 2
      max_restarts: 100
    environment:
      - NODE_ENV=development