name = "livestore-threadbot"
main = "src/worker.ts"
compatibility_date = "2025-05-18"

[durable_objects]
bindings = [{ name = "BOT_GATEWAY", class_name = "BotGateway" }]

[[migrations]]
tag = "v1"
new_classes = ["BotGateway"]

[triggers]
crons = ["*/15 * * * *"] # keeps the WebSocket from idling out

[observability.logs]
enabled = true

[vars]
# Set via admin panel as secrets or `wrangler secret put`
# DISCORD_TOKEN
# OPENAI_KEY
